language: python

python:
  # - 2.7
  - 3.3
  # - 3.4
env:
  - VIM_VERSION="74"
  # - VIM_VERSION="NEOVIM"

matrix:
  allow_failures:
    # TODO(sirver): Neovim does not play well with our testing right now.
    - env: VIM_VERSION="NEOVIM"

install: sudo ./install_vim.sh "${VIM_VERSION}" "$(python --version 2>&1)"

before_script:
  - tmux new -d -s vim

script: ./test_all.py -v --plugins --session vim
